version: "3.8"

services:
  product-service:
    build: .  # This tells Docker Compose to build the image locally using the Dockerfile
    image: productservice:latest  # Matches the tag you used in Jenkinsfile
    container_name: product-service
    env_file:
      - .env  # Pass your PORT and MONGO_URL
    ports:
      - "5001:5001"  # Maps host port 5001 to container port 5001
    restart: unless-stopped
    networks:
      - app

networks:
  app:
