version: "3.8"

services:
  product-service:
    image: productservice:latest # Same as Jenkins build tag
    container_name: product-service
    env_file:
      - .env
    ports:
      - "5001:5001"
    restart: unless-stopped
    networks:
      - app

networks:
  app:
